### ISSUE TITLE
Logo design contribution

### ISSUE THREAD

**Issue by saifulfrank** [joominyeo/GPSMS#1]
Hi
I want to make a logo for this projects if you have any requirements then let me know.its totally free for open source projects.

**Comment by joominyeo** [comment]
Sure. Don't really have any requirements; be creative!
If you have multiple designs for us, I will pitch it to the rest of the team and vote on it.

**Comment by saifulfrank** [comment]
I have created three logos for you. which one of your choices tell me that I'll give you that source file. If you think something needs to be changed then you can tell me I'll change.

![gpssms](https://user-images.githubusercontent.com/37498811/41061160-8f59b204-69f3-11e8-96c8-0a4957672a34.png)
![gpssms1](https://user-images.githubusercontent.com/37498811/41061163-8fb5affa-69f3-11e8-900b-61247a6e0036.png)
![gpssms2](https://user-images.githubusercontent.com/37498811/41061165-8ff49828-69f3-11e8-8a71-e2f0c7b4e118.png)

**Comment by joominyeo** [comment]
Just shared it with the rest of the team and we really like the first design.
One thing that we discussed is that our project uses cellular networks, but the top of the design seems to indicate the use of Wi-Fi.

What is your thought on changing that top part to allude the use of cell towers rather than Wi-Fi?
And giving the logo a more blue-ish feel?

We really like your design; and hope that you will continue to help us.
We will be presenting this project at a conference soon.
How would you like to be credited for the design?

Thanks and cheers!

**Comment by saifulfrank** [comment]
Check the updated files. Here 2 type of cellular network added. Let me now your opinion.
 Thank you

![gpssmss](https://user-images.githubusercontent.com/37498811/41087723-2d633180-6a5f-11e8-8021-96c5900eb448.png)
![gpssmsss](https://user-images.githubusercontent.com/37498811/41087725-2f047e0e-6a5f-11e8-85b7-182566d0eebc.png)

**Comment by saifulfrank** [comment]
if need any changes then let me know.

**Comment by joominyeo** [comment]
The first one looks the best!
Can you give the logo a little bit more or a brighter blue hue?
Thanks.

**Comment by saifulfrank** [comment]
of course! I will send you updated file very soon
thank you

**Comment by saifulfrank** [comment]
check this please I have added 3 different colors.

![gpsms](https://user-images.githubusercontent.com/37498811/41239515-4a802d3c-6dba-11e8-840c-21177932275c.png)
![gpsms1](https://user-images.githubusercontent.com/37498811/41239516-4ac91f7e-6dba-11e8-889a-d3ec0ad44a5e.png)
![gpsms2](https://user-images.githubusercontent.com/37498811/41239518-4b188f3c-6dba-11e8-90fd-e6d5e2fe4585.png)

**Comment by joominyeo** [comment]
We like the last color the most.
The exact design and color and the original size (bigger) and it will be perfect!
Can you send me the png file?

**Comment by joominyeo** [comment]
Also, How would you like to be credited for the logo?
Your logo will be displayed on these mediums:

1) Presentation slides
2) Project report
3) My personal website

**Comment by saifulfrank** [comment]
Great! you can give a credit on the readme.
Here is google drive link. You will find all necessary files and editable source file there
<a href="https://drive.google.com/open?id=13leeWp668OdcMcNIDsZcGcmeIYbOtFGt">Download</a>
<a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>

**Comment by saifulfrank** [comment]
please check pull #3

**Comment by joominyeo** [comment]
Do you have a specific format or link you'd like me to add in the readme file?

**Comment by saifulfrank** [comment]
You can add my github profile link there.
thank you 
https://github.com/saifulfrank

**Comment by joominyeo** [comment]
Coolio.
We really appreciate your contribution.
